const emojipedia = [
  {
    id: 1,
    emoji: "😀",
    name: "Grinning Face",
    meaning: "Represents happiness or excitement.",
  },
  {
    id: 2,
    emoji: "😁",
    name: "Beaming Face With Smiling Eyes",
    meaning: "Big grin with happy eyes, shows joy or enthusiasm.",
  },
  {
    id: 3,
    emoji: "😂",
    name: "Face With Tears of Joy",
    meaning: "Used to show laughter or something very funny.",
  },
  {
    id: 4,
    emoji: "🤣",
    name: "Rolling On The Floor Laughing",
    meaning: "Extreme laughter, as if rolling on the floor.",
  },
  {
    id: 5,
    emoji: "😃",
    name: "Smiling Face With Open Mouth",
    meaning: "Expresses cheerfulness and joy.",
  },
  {
    id: 6,
    emoji: "😄",
    name: "Smiling Face With Smiling Eyes",
    meaning: "Happiness and positive vibes.",
  },
  {
    id: 7,
    emoji: "😅",
    name: "Smiling Face With Sweat",
    meaning: "Relief or nervous laughter.",
  },
  {
    id: 8,
    emoji: "😆",
    name: "Grinning Squinting Face",
    meaning: "Big laugh or excitement.",
  },
  {
    id: 9,
    emoji: "😉",
    name: "Winking Face",
    meaning: "Playful, flirtatious, or joking tone.",
  },
  {
    id: 10,
    emoji: "😊",
    name: "Smiling Face With Blushing Cheeks",
    meaning: "Shy happiness or gratitude.",
  },
  {
    id: 11,
    emoji: "😋",
    name: "Face Savoring Food",
    meaning: "Delicious! Used for tasty food.",
  },
  {
    id: 12,
    emoji: "😎",
    name: "Smiling Face With Sunglasses",
    meaning: "Cool, confident, or chill vibes.",
  },
  {
    id: 13,
    emoji: "😍",
    name: "Smiling Face With Heart-Eyes",
    meaning: "Love, admiration, or infatuation.",
  },
  {
    id: 14,
    emoji: "😘",
    name: "Face Blowing a Kiss",
    meaning: "Affection, love, or gratitude.",
  },
  {
    id: 15,
    emoji: "🥰",
    name: "Smiling Face With Hearts",
    meaning: "Feeling loved or affectionate.",
  },
  {
    id: 16,
    emoji: "😗",
    name: "Kissing Face",
    meaning: "General affection, less romantic.",
  },
  {
    id: 17,
    emoji: "😙",
    name: "Kissing Face With Smiling Eyes",
    meaning: "Happy affection or gratitude.",
  },
  {
    id: 18,
    emoji: "😚",
    name: "Kissing Face With Closed Eyes",
    meaning: "Romantic or loving gesture.",
  },
  {
    id: 19,
    emoji: "🙂",
    name: "Slightly Smiling Face",
    meaning: "Polite happiness or mild positivity.",
  },
  {
    id: 20,
    emoji: "🤗",
    name: "Hugging Face",
    meaning: "Offering a virtual hug.",
  },
  {
    id: 21,
    emoji: "🤩",
    name: "Star-Struck",
    meaning: "Amazement or admiration, often for celebrities or cool things.",
  },
  {
    id: 22,
    emoji: "🤔",
    name: "Thinking Face",
    meaning: "Used when considering or questioning something.",
  },
  {
    id: 23,
    emoji: "🤨",
    name: "Raised Eyebrow Face",
    meaning: "Suspicion or disapproval.",
  },
  {
    id: 24,
    emoji: "😐",
    name: "Neutral Face",
    meaning: "No particular emotion or unimpressed.",
  },
  {
    id: 25,
    emoji: "😑",
    name: "Expressionless Face",
    meaning: "Silence or lack of interest.",
  },
  {
    id: 26,
    emoji: "😶",
    name: "Face Without Mouth",
    meaning: "Speechless or silent.",
  },
  {
    id: 27,
    emoji: "🙄",
    name: "Face With Rolling Eyes",
    meaning: "Sarcasm, annoyance, or disbelief.",
  },
  {
    id: 28,
    emoji: "😏",
    name: "Smirking Face",
    meaning: "Flirtatious or smug expression.",
  },
  {
    id: 29,
    emoji: "😒",
    name: "Unamused Face",
    meaning: "Displeasure, dissatisfaction, or boredom.",
  },
  {
    id: 30,
    emoji: "😞",
    name: "Disappointed Face",
    meaning: "Sadness or regret.",
  },
  {
    id: 31,
    emoji: "😔",
    name: "Pensive Face",
    meaning: "Sad, thoughtful, or regretful.",
  },
  { id: 32, emoji: "😟", name: "Worried Face", meaning: "Concern or unease." },
  {
    id: 33,
    emoji: "😕",
    name: "Confused Face",
    meaning: "Uncertainty or confusion.",
  },
  {
    id: 34,
    emoji: "🙁",
    name: "Slightly Frowning Face",
    meaning: "Mild sadness or disappointment.",
  },
  {
    id: 35,
    emoji: "☹️",
    name: "Frowning Face",
    meaning: "Stronger sadness or disapproval.",
  },
  {
    id: 36,
    emoji: "😣",
    name: "Persevering Face",
    meaning: "Trying hard or struggling.",
  },
  {
    id: 37,
    emoji: "😖",
    name: "Confounded Face",
    meaning: "Frustration or distress.",
  },
  {
    id: 38,
    emoji: "😫",
    name: "Tired Face",
    meaning: "Exhaustion or fatigue.",
  },
  {
    id: 39,
    emoji: "😩",
    name: "Weary Face",
    meaning: "Feeling overwhelmed or tired.",
  },
  {
    id: 40,
    emoji: "🥺",
    name: "Pleading Face",
    meaning: "Begging, puppy eyes, or emotional request.",
  },
  {
    id: 41,
    emoji: "😢",
    name: "Crying Face",
    meaning: "Sadness or heartbreak.",
  },
  {
    id: 42,
    emoji: "😭",
    name: "Loudly Crying Face",
    meaning: "Extreme sadness or emotional breakdown.",
  },
  {
    id: 43,
    emoji: "😤",
    name: "Face With Steam From Nose",
    meaning: "Frustration, anger, or pride.",
  },
  { id: 44, emoji: "😠", name: "Angry Face", meaning: "Anger or annoyance." },
  {
    id: 45,
    emoji: "😡",
    name: "Pouting Face",
    meaning: "Stronger anger or rage.",
  },
  {
    id: 46,
    emoji: "🤬",
    name: "Face With Symbols Over Mouth",
    meaning: "Swearing or extreme anger.",
  },
  {
    id: 47,
    emoji: "🤯",
    name: "Exploding Head",
    meaning: "Mind blown or extreme shock.",
  },
  {
    id: 48,
    emoji: "😳",
    name: "Flushed Face",
    meaning: "Embarrassment or surprise.",
  },
  {
    id: 49,
    emoji: "🥵",
    name: "Hot Face",
    meaning: "Feeling hot, sweaty, or flustered.",
  },
  {
    id: 50,
    emoji: "🥶",
    name: "Cold Face",
    meaning: "Feeling freezing or cold.",
  },
  {
    id: 51,
    emoji: "😱",
    name: "Face Screaming in Fear",
    meaning: "Extreme shock or terror.",
  },
  { id: 52, emoji: "😨", name: "Fearful Face", meaning: "Fear or worry." },
  {
    id: 53,
    emoji: "😰",
    name: "Anxious Face With Sweat",
    meaning: "Nervous or anxious.",
  },
  {
    id: 54,
    emoji: "😥",
    name: "Sad but Relieved Face",
    meaning: "Relief after stress.",
  },
  {
    id: 55,
    emoji: "😓",
    name: "Downcast Face With Sweat",
    meaning: "Disappointment or tiredness.",
  },
  {
    id: 56,
    emoji: "🤤",
    name: "Drooling Face",
    meaning: "Desire for food or attraction.",
  },
  { id: 57, emoji: "😴", name: "Sleeping Face", meaning: "Sleep or boredom." },
  {
    id: 58,
    emoji: "😪",
    name: "Sleepy Face",
    meaning: "Drowsiness or fatigue.",
  },
  {
    id: 59,
    emoji: "🤢",
    name: "Nauseated Face",
    meaning: "Feeling sick or disgusted.",
  },
  {
    id: 60,
    emoji: "🤮",
    name: "Face Vomiting",
    meaning: "Extreme disgust or sickness.",
  },
  {
    id: 61,
    emoji: "🤧",
    name: "Sneezing Face",
    meaning: "Feeling sick or having a cold.",
  },
  {
    id: 62,
    emoji: "🥴",
    name: "Woozy Face",
    meaning: "Dizzy, drunk, or confused.",
  },
  {
    id: 63,
    emoji: "😵",
    name: "Dizzy Face",
    meaning: "Confusion or dizziness.",
  },
  {
    id: 64,
    emoji: "🤕",
    name: "Face With Head-Bandage",
    meaning: "Injury or recovery.",
  },
  {
    id: 65,
    emoji: "🤒",
    name: "Face With Thermometer",
    meaning: "Feeling sick or feverish.",
  },
  {
    id: 66,
    emoji: "🤠",
    name: "Cowboy Hat Face",
    meaning: "Yeehaw! Fun or adventurous.",
  },
  {
    id: 67,
    emoji: "🥳",
    name: "Partying Face",
    meaning: "Celebration or excitement.",
  },
  {
    id: 68,
    emoji: "😇",
    name: "Smiling Face With Halo",
    meaning: "Innocence or goodness.",
  },
  {
    id: 69,
    emoji: "🤓",
    name: "Nerd Face",
    meaning: "Geekiness or intelligence.",
  },
  {
    id: 70,
    emoji: "🧐",
    name: "Face With Monocle",
    meaning: "Serious observation or curiosity.",
  },
  {
    id: 71,
    emoji: "😈",
    name: "Smiling Face With Horns",
    meaning: "Mischievous or playful evil.",
  },
  {
    id: 72,
    emoji: "👿",
    name: "Angry Face With Horns",
    meaning: "Serious anger or evil intent.",
  },
  {
    id: 73,
    emoji: "💀",
    name: "Skull",
    meaning: "Death, danger, or dark humor.",
  },
  {
    id: 74,
    emoji: "☠️",
    name: "Skull and Crossbones",
    meaning: "Deadly or toxic warning.",
  },
  { id: 75, emoji: "👻", name: "Ghost", meaning: "Fun spooky or silly ghost." },
  {
    id: 76,
    emoji: "👽",
    name: "Alien",
    meaning: "Extraterrestrial or something weird.",
  },
  {
    id: 77,
    emoji: "🤖",
    name: "Robot Face",
    meaning: "Robotic or emotionless behavior.",
  },
  {
    id: 78,
    emoji: "😺",
    name: "Smiling Cat Face",
    meaning: "Happy or playful mood (cat version).",
  },
  {
    id: 79,
    emoji: "😸",
    name: "Grinning Cat Face",
    meaning: "Cheerful cat vibe.",
  },
  {
    id: 80,
    emoji: "😹",
    name: "Cat Face With Tears of Joy",
    meaning: "Cat laughing hard.",
  },
  {
    id: 81,
    emoji: "😻",
    name: "Smiling Cat With Heart-Eyes",
    meaning: "Cat in love.",
  },
  {
    id: 82,
    emoji: "😼",
    name: "Cat With Wry Smile",
    meaning: "Playful, cheeky cat.",
  },
  {
    id: 83,
    emoji: "🙀",
    name: "Weary Cat Face",
    meaning: "Cat shocked or scared.",
  },
  { id: 84, emoji: "😿", name: "Crying Cat Face", meaning: "Sad cat." },
  {
    id: 85,
    emoji: "😾",
    name: "Pouting Cat Face",
    meaning: "Annoyed cat mood.",
  },
  {
    id: 86,
    emoji: "💩",
    name: "Pile of Poo",
    meaning: "Jokingly bad or silly situation.",
  },
  { id: 87, emoji: "🔥", name: "Fire", meaning: "Awesome, hot, or lit." },
  { id: 88, emoji: "💧", name: "Droplet", meaning: "Sweat, water, or tears." },
  {
    id: 89,
    emoji: "🌈",
    name: "Rainbow",
    meaning: "Happiness, hope, or diversity.",
  },
  {
    id: 90,
    emoji: "🌞",
    name: "Sun With Face",
    meaning: "Warmth and positivity.",
  },
  {
    id: 91,
    emoji: "🌝",
    name: "Full Moon With Face",
    meaning: "Goofy or mysterious tone.",
  },
  {
    id: 92,
    emoji: "🌚",
    name: "New Moon Face",
    meaning: "Creepy or sarcastic tone.",
  },
  {
    id: 93,
    emoji: "🌟",
    name: "Glowing Star",
    meaning: "Something special or magical.",
  },
  {
    id: 94,
    emoji: "⭐",
    name: "Star",
    meaning: "Success, fame, or achievement.",
  },
  {
    id: 95,
    emoji: "⚡",
    name: "High Voltage",
    meaning: "Energy, power, or excitement.",
  },
  {
    id: 96,
    emoji: "💥",
    name: "Collision",
    meaning: "Explosion, impact, or shock.",
  },
  {
    id: 97,
    emoji: "💫",
    name: "Dizzy Symbol",
    meaning: "Feeling dazed or starstruck.",
  },
  {
    id: 98,
    emoji: "💦",
    name: "Sweat Droplets",
    meaning: "Motion, water, or emphasis (contextual 😏).",
  },
  {
    id: 99,
    emoji: "💨",
    name: "Dashing Away",
    meaning: "Speed, motion, or leaving quickly.",
  },
  {
    id: 100,
    emoji: "💪",
    name: "Flexed Biceps",
    meaning: "Strength, determination, or motivation.",
  },
  {
    id: 101,
    emoji: "❤️",
    name: "Red Heart",
    meaning: "Love, affection, or deep emotion.",
  },
  {
    id: 102,
    emoji: "💙",
    name: "Blue Heart",
    meaning: "Trust, loyalty, or calm love.",
  },
  {
    id: 103,
    emoji: "💚",
    name: "Green Heart",
    meaning: "Nature, growth, or jealousy.",
  },
  {
    id: 104,
    emoji: "💛",
    name: "Yellow Heart",
    meaning: "Friendship, happiness, or positivity.",
  },
  {
    id: 105,
    emoji: "🖤",
    name: "Black Heart",
    meaning: "Sadness, dark humor, or goth vibes.",
  },
  {
    id: 106,
    emoji: "💖",
    name: "Sparkling Heart",
    meaning: "Exciting love or strong affection.",
  },
  {
    id: 107,
    emoji: "💝",
    name: "Heart With Ribbon",
    meaning: "Gift of love or Valentine's Day.",
  },
  {
    id: 108,
    emoji: "💗",
    name: "Growing Heart",
    meaning: "Love growing or blushing feelings.",
  },
  {
    id: 109,
    emoji: "💓",
    name: "Beating Heart",
    meaning: "Heartbeat, excitement, or love pulse.",
  },
  {
    id: 110,
    emoji: "💔",
    name: "Broken Heart",
    meaning: "Heartbreak or emotional pain.",
  },
  {
    id: 111,
    emoji: "💘",
    name: "Heart With Arrow",
    meaning: "Love at first sight or Cupid.",
  },
  {
    id: 112,
    emoji: "💕",
    name: "Two Hearts",
    meaning: "Couple love or mutual affection.",
  },
  {
    id: 113,
    emoji: "💞",
    name: "Revolving Hearts",
    meaning: "Flirty love or whirlwind romance.",
  },
  {
    id: 114,
    emoji: "💟",
    name: "Heart Decoration",
    meaning: "General love or heart symbol.",
  },
  {
    id: 115,
    emoji: "❣️",
    name: "Heavy Heart Exclamation",
    meaning: "Emphatic love or excitement.",
  },
  {
    id: 116,
    emoji: "♥️",
    name: "Heart Suit",
    meaning: "Classic heart symbol or cards.",
  },
  {
    id: 117,
    emoji: "✨",
    name: "Sparkles",
    meaning: "Magic, new, or something special.",
  },
  {
    id: 118,
    emoji: "⭐",
    name: "White Medium Star",
    meaning: "Rating, favorite, or excellence.",
  },
  {
    id: 119,
    emoji: "🌟",
    name: "Glowing Star",
    meaning: "Achievement or star quality.",
  },
  {
    id: 120,
    emoji: "✨",
    name: "Sparkling Heart",
    meaning: "Magical love or enchantment.",
  },
  {
    id: 121,
    emoji: "🎉",
    name: "Party Popper",
    meaning: "Celebration or happy event.",
  },
  {
    id: 122,
    emoji: "🎊",
    name: "Confetti Ball",
    meaning: "Party time or congratulations.",
  },
  {
    id: 123,
    emoji: "🎈",
    name: "Balloon",
    meaning: "Party, celebration, or floating ideas.",
  },
  {
    id: 124,
    emoji: "🎁",
    name: "Wrapped Gift",
    meaning: "Present, surprise, or birthday.",
  },
  {
    id: 125,
    emoji: "🎂",
    name: "Birthday Cake",
    meaning: "Birthday wishes or celebration.",
  },
  {
    id: 126,
    emoji: "🍰",
    name: "Shortcake",
    meaning: "Dessert, sweet treat, or cuteness.",
  },
  {
    id: 127,
    emoji: "🍕",
    name: "Pizza",
    meaning: "Food, fun, or casual hangout.",
  },
  {
    id: 128,
    emoji: "🍔",
    name: "Hamburger",
    meaning: "Fast food or American classic.",
  },
  {
    id: 129,
    emoji: "🍟",
    name: "French Fries",
    meaning: "Snack or side dish.",
  },
  {
    id: 130,
    emoji: "🌮",
    name: "Taco",
    meaning: "Mexican food or Tuesday vibes.",
  },
  {
    id: 131,
    emoji: "🌯",
    name: "Burrito",
    meaning: "Hearty meal or wrapped up.",
  },
  {
    id: 132,
    emoji: "🍣",
    name: "Sushi",
    meaning: "Japanese cuisine or fresh food.",
  },
  {
    id: 133,
    emoji: "🍦",
    name: "Soft Ice Cream",
    meaning: "Dessert treat or summer fun.",
  },
  {
    id: 134,
    emoji: "🍩",
    name: "Doughnut",
    meaning: "Sweet snack or cop stereotype.",
  },
  {
    id: 135,
    emoji: "🍪",
    name: "Cookie",
    meaning: "Baking, snack, or 'that's the way the cookie crumbles'.",
  },
  {
    id: 136,
    emoji: "🍫",
    name: "Chocolate Bar",
    meaning: "Sweet treat or comfort food.",
  },
  {
    id: 137,
    emoji: "🍬",
    name: "Candy",
    meaning: "Sweet, sugar rush, or eye candy.",
  },
  {
    id: 138,
    emoji: "🍭",
    name: "Lollipop",
    meaning: "Candy treat or playful.",
  },
  {
    id: 139,
    emoji: "🍉",
    name: "Watermelon",
    meaning: "Summer fruit or refreshing.",
  },
  {
    id: 140,
    emoji: "🍎",
    name: "Red Apple",
    meaning: "Healthy, teacher gift, or temptation.",
  },
];

export default emojipedia;
